### PR TITLE
NGINX: verify SSL connection to GitHub.

### PR DESCRIPTION
**Pull request by PiotrSikora**

### CODE REVIEW

**Comment by PiotrSikora** [comment]
Note: the CA certificate could be stored as a `configMap` instead of a `secret`, but then it should probably be committed in the repo.

Let me know if you prefer that.

**Comment by ayj** [comment]
You could keep it a secret and commit the YAML file to the repo since this public, e.g.

```bash
kubectl create secret generic cacerts --from-file=DigiCertHighAssuranceEVRootCA.pem --dry-run -o yaml > upstream-ca-cert-secret.yaml
```

If so, it would be good to update the corresponding scripts too, e.g. canary.sh, Makefile.

**Comment by PiotrSikora** [comment]
Yeah, but is there any point in keeping it a `secret` instead of `configMap`, then?

**Comment by PiotrSikora** [comment]
(the argument for a out-of-repo secret is that _some_ self-signed CA certificates might be private, in the future / generic case)

**Comment by ayj** [comment]
Either resource would be fine for this particular case.

**Comment by PiotrSikora** [comment]
Done.

**Comment by PiotrSikora** [comment]
@ayj Ping.

**Pull request merged**
