### PR TITLE
Build script to generate historical versions

### LINKED ISSUE #33: add archive.istio.io
We want 1 static site with all the version archived

related to https://github.com/istio/istio.github.io/pull/833

cc @geeknoid

### PR DESCRIPTION
**Pull request by ldemailly**
Fixes #33 

See result at

https://archive.istio.io/

### CODE REVIEW

**Comment by ldemailly** [comment]
I wasn't 100% done :)

**Comment by geeknoid** [comment]
Sorry :-)

**Comment by ldemailly** [comment]
I merged a follow up with some minimal patching of the header for now

but if we want the cut navigation one we would need to make actual branches for 0.2 onward
and apply in each branch

also I noticed some of the about links are broken and seem to rely on redirect that isn't there

**Comment by geeknoid** [comment]
Hmm. There shouldn't be a redirect for that. When I go to
archive.istio.io/v0.4 and click on About, it doesn't work. The links seems
right, but the file just doesn't seem to be there. Could it be a permission
problem on the "about" directory?

**Comment by ldemailly** [comment]
I added the redirect it will work now if you reload - see the other pr #37

**Pull request merged**
