### PR TITLE
Add new -sync-interval to fortio sites

### PR DESCRIPTION
**Pull request by ldemailly**
Only push after https://github.com/istio/fortio/pull/244 is released
(Fortio 0.10.1)

### CODE REVIEW

**Comment by ldemailly** [comment]
@rkpagadala I pushed it to https://fortio-daily.istio.io/

There seems to be quite a lot of variability, I wonder if the clusters are the same ?

**Comment by rkpagadala** [comment]
@ldemailly the clusters vary for each run

**Comment by ldemailly** [comment]
this is deployed already so should be merged

**Comment by ayj** [comment]
Can you re-enable my write access as well?

**Comment by geeknoid** [comment]
Sorry, I missed this in the usual mass of GitHub emails.

Both Laurent and Jason are in the Admin Sites Hackers team, which has write access to this repo. We don't have any protected branches configured in this repo. So it really should just be working for you. I'll keep looking for the magic bit...

**Comment by geeknoid** [comment]
Aha, found a bit and flipped it. How's it working now?

**Comment by ldemailly** [comment]
cool thanks ! what was it ?

**Comment by geeknoid** [comment]
​For some reason, the "Restrict who can push to this branch" option was on.
I just turned it off.​

**Pull request merged**
