### PR TITLE
Add preliminary.istio.io and redirect istio.io to current-istio-io.firebaseapp.com

### PR DESCRIPTION
**Pull request by ayj**
fyi @geeknoid 

This isn't perfect. `current-istio-io.firebaseapp.com` currently expects `host` to be `current-istio-io.firebaseapp.com` and not `istio.io`. Any redirects generated by firebase will point to `current-istio-io.firebaseapp.com/path/to/redirected` and not to the vanity domain `istio.io/path/to/redirected`. I didn't see anything in https://firebase.google.com/docs/hosting/full-config to override this setting.

### CODE REVIEW

**Comment by ldemailly** [comment]
how is archive.istio.io just working ? I don't remember doing anything special except "connect domain"

**Comment by ayj** [comment]
`archive.istio.io` subdomain is fully managed by firebase. We could do the same for `istio.io`, but we'd need to handle the golang import vanity domain redirects as well. Firebase has some support for cloud functions, but I haven't looked to closely at it yet for this purpose. 

If we're considering that option, I would also want to look into https://www.netlify.com for serving our static content.  Theres some options for deploying directly from git. For example, I just created https://optimistic-ardinghelli-599e39.netlify.com from https://github.com/ayj/istio.github.io. Pushing to `master` triggers a new build that is automatically published.

**Comment by ldemailly** [comment]
I guess you should be able to configure nginx as reverse proxy from firebase origin server as long as html generated there knows what root url  it is supposed to be on (or only use relative urls but unfortunately we don't do that) - a bit like v-0.1/ was ?

root/site url is a setting in jekyll so it should be fine ?

**Comment by ayj** [comment]
> root/site url is a setting in jekyll so it should be fine ?

In theory :) github pages does "trailing slash" redirects (see https://stackoverflow.com/questions/33270605/github-pages-trailing-slashes). Firebase doesn't (see below). I'm not sure if there are any other auto-redirect differences between sites.

```bash
# archive.istio.io served by firebase
$ curl -s -I https://archive.istio.io/v0.4/docs/reference | grep -e ^location -e ^HTTP
HTTP/2 200 

# istio.io served by github pages
$ curl -s -I https://istio.io/docs/reference | grep -e ^location -e ^HTTP
HTTP/2 301 
location: http://istio.io/docs/reference/
```

**Comment by ldemailly** [comment]
I though I solved those with https://github.com/istio/admin-sites/blob/master/archive.istio.io/firebase.json#L16

but we do have bad urls in istio.io source tree that wrongly assume that foo and foo/ and foo.html are all interchangeable while the one with / is definitively very different as it is in a different directory so all relative urls would not work

I think we are hiding some of those by having very few relative urls

**Comment by ayj** [comment]
> The cleanUrls setting is an optional parameter that, when true, will automatically drop the .html extension from uploaded file URLs. If a .html extension is added, a 301 redirect will be performed to the same path without the .html extension.

This particular 301 is relative (see below), but it doesn't seem to make _alll_ redirects relative. We might be okay for now re: relative redirects, but it is fragile.

```bash
$ curl -s -I https://archive.istio.io/v0.4/docs/reference/config/traffic-rules/routing-rules.html | grep -e ^HTTP -e location
HTTP/2 301 
location: /v0.4/docs/reference/config/traffic-rules/routing-rules
```

**Comment by geeknoid** [comment]
Why is preliminary.istio.io mentioned in here? I thought that could be completely handled via a DNS entry pointing to the GitHub Pages site.

So netify.com will also run Jekyll? Do they use the same options as GitHub Pages? Is it free or do we need to pay for this somehow?

**Comment by ayj** [comment]
`preliminary.istio.io` is served from github pages which, last I checked, didn't allow for https with custom (sub)domains.

Netlify can build with jekyll. re: supporting same options, they do expect a `Gemfile.lock`. See https://www.netlify.com/blog/2015/10/28/a-step-by-step-guide-jekyll-3.0-on-netlify.

There's a free tier for open source projects (see https://www.netlify.com/open-source). Kubernetes cut off to netlify last year (see https://github.com/kubernetes/k8s.io/pull/70).

**Comment by geeknoid** [comment]
I have no issue with going to netlify.com if you think that'll work better.

**Comment by ldemailly** [comment]
it's not exactly istio on istio ... but whichever gets the job done for now I suppose

**Comment by ldemailly** [comment]
how do we safely test the waters on this ?
(ie check it doesn't break anything; for instance go get etc...)

or just make the change early in the day such as we fix forward/revert if needed?
Thu or Monday (not friday) then ?

**Comment by geeknoid** [comment]
Yep, let's flip the switch in the morning, do manual testing to make sure
it's OK, and then wait and see...


On Wed, Mar 14, 2018 at 10:51 PM, Laurent Demailly <notifications@github.com

**Comment by ayj** [comment]
These changes are live. Can we merge?

**Pull request merged**
