### PR TITLE
point istio.io at v0.1 docs and istio.io/v-0.2 at master

### PR DESCRIPTION
**Pull request by ayj**

### CODE REVIEW

**Comment by ldemailly** [comment]
I think we should preserve https://istio.io/v-0.1/docs/ during the swap

**Comment by ayj** [comment]
istio.io should continue to point to master if we're really concerned about preserving links. Otherwise we'll end up trying to do a directory-by-directory (or worse, link-by-link) scan of the website contents to determine how it is presented to the user.

**Comment by ayj** [comment]
And this is only intended to be short lived (<2 weeks) while we update the docs?

**Comment by ldemailly** [comment]
it takes a while for search engines to index stuff and see changes so I just would like to avoid dead links

I completely agree that per directory is error prone yet that's where we're headed, but if at least we'd limit it to docs/ maybe it's easier - but it is really odd to say github master is live on istio.io except for docs/ which are v0.1 branch and the master docs goes to v0.2

**Comment by ldemailly** [comment]
looks like we changed our collective mind again and stick with the current master vs v0.1 setup

**Pull request closed without merging**
